// Getting the wallet into a state where it can actually pay for a transaction.
//
// Two separate things have to be true, and only the first is obvious:
//   1. the unshielded address holds NIGHT, and
//   2. those NIGHT UTXOs are registered for dust generation.
// NIGHT alone does not pay fees -- dust does, and dust is generated by
// registered NIGHT. A wallet with a healthy NIGHT balance and no dust will fail
// to submit anything, which is a confusing way to learn this.

import { UnshieldedTokenType, unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { type FacadeState, type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { createKeystore, type UnshieldedWalletState } from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { UnshieldedAddress } from '@midnight-ntwrk/wallet-sdk-address-format';
import { getNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { FaucetClient, type EnvironmentConfiguration } from '@midnight-ntwrk/testkit-js';
import type { Logger } from 'pino';
import * as Rx from 'rxjs';

const isComplete = (progress: unknown): boolean => {
  if (!progress || typeof progress !== 'object') return false;
  const candidate = progress as { isStrictlyComplete?: unknown };
  if (typeof candidate.isStrictlyComplete !== 'function') return false;
  return (candidate.isStrictlyComplete as () => boolean)();
};

const isSynced = (state: FacadeState): boolean =>
  isComplete(state.shielded.state.progress) &&
  isComplete(state.dust.state.progress) &&
  isComplete(state.unshielded.progress);

export const syncWallet = (logger: Logger, wallet: WalletFacade, throttleTime = 2_000): Promise<FacadeState> => {
  logger.info('Syncing wallet...');
  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(throttleTime),
      Rx.filter(isSynced),
      Rx.tap((state) =>
        logger.info(
          `Synced. unshielded=${JSON.stringify(state.unshielded.balances)} dust=${state.dust.balance(new Date())}`,
        ),
      ),
    ),
  );
};

export const unshieldedAddressOf = (state: UnshieldedWalletState): string =>
  UnshieldedAddress.codec.encode(getNetworkId(), state.address).toString();

/**
 * Waits until the unshielded address holds NIGHT, optionally asking the faucet
 * for some first. `fundFromFaucet` is off by default: it is an outbound request
 * and the caller should opt into it.
 */
export const waitForNight = async (
  logger: Logger,
  wallet: WalletFacade,
  env: EnvironmentConfiguration,
  fundFromFaucet = false,
  tokenType: UnshieldedTokenType = unshieldedToken(),
  throttleTime = 2_000,
): Promise<UnshieldedWalletState> => {
  const initial = await Rx.firstValueFrom(wallet.unshielded.state);
  logger.info(`Unshielded address: ${unshieldedAddressOf(initial)}`);

  if (fundFromFaucet) {
    if (!env.faucet) throw new Error('no faucet configured for this environment');
    logger.info('Requesting tokens from faucet...');
    await new FaucetClient(env.faucet, logger).requestTokens(unshieldedAddressOf(initial));
  }

  const balance = initial.balances[tokenType.raw];
  if (balance !== undefined && balance > 0n) {
    logger.info(`NIGHT balance: ${balance}`);
    return initial;
  }

  logger.info('No NIGHT yet -- waiting for funds to land...');
  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(throttleTime),
      Rx.filter((state) => isSynced(state) && (state.unshielded.balances[tokenType.raw] ?? 0n) > 0n),
      Rx.tap((state) => logger.info(`NIGHT balance: ${state.unshielded.balances[tokenType.raw]}`)),
      Rx.map((state) => state.unshielded),
    ),
  );
};

/** The HD key the unshielded keystore is built from -- role 0, account 0, index 0. */
const unshieldedSeedOf = (seed: string): Uint8Array => {
  const result = HDWallet.fromSeed(Buffer.from(seed, 'hex'));
  if (result.type !== 'seedOk') throw new Error('seed rejected by HDWallet');
  const derived = result.hdWallet.selectAccount(0).selectRole(Roles.NightExternal).deriveKeyAt(0);
  if (derived.type !== 'keyDerived') throw new Error('key derivation out of bounds');
  return derived.key;
};

/**
 * Registers unregistered NIGHT UTXOs for dust generation, so the wallet can pay
 * fees. Returns the tx id, or undefined when there was nothing to register.
 */
export const registerForDust = async (
  logger: Logger,
  seed: string,
  unshielded: UnshieldedWalletState,
  wallet: WalletFacade,
): Promise<string | undefined> => {
  const utxos = unshielded.availableCoins.filter((coin) => !coin.meta.registeredForDustGeneration);
  if (utxos.length === 0) {
    logger.info('All NIGHT UTXOs are already registered for dust generation.');
    return undefined;
  }

  const dustState = await wallet.dust.waitForSyncedState();
  const keystore = createKeystore(unshieldedSeedOf(seed), getNetworkId());

  logger.info(`Registering ${utxos.length} UTXO(s) for dust generation...`);
  const recipe = await wallet.registerNightUtxosForDustGeneration(
    utxos,
    keystore.getPublicKey(),
    (payload) => keystore.signData(payload),
    dustState.address,
  );
  const txId = await wallet.submitTransaction(await wallet.finalizeRecipe(recipe));
  logger.info(`Dust registration submitted: ${txId}`);

  const dustBalance = await Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.filter((s) => s.dust.balance(new Date()) > 0n),
      Rx.map((s) => s.dust.balance(new Date())),
    ),
  );
  logger.info(`Dust balance: ${dustBalance}`);
  return txId;
};
