// Getting the wallet into a state where it can actually pay for a transaction.
//
// Two separate things have to be true, and only the first is obvious:
//   1. the unshielded address holds NIGHT, and
//   2. those NIGHT UTXOs are registered for dust generation.
// NIGHT alone does not pay fees -- dust does, and dust is generated by
// registered NIGHT. A wallet with a healthy NIGHT balance and no dust will fail
// to submit anything, which is a confusing way to learn this.

import { UnshieldedTokenType, unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { type FacadeState, type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { createKeystore, type UnshieldedWalletState } from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { UnshieldedAddress } from '@midnight-ntwrk/wallet-sdk-address-format';
import { getNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { FaucetClient, type EnvironmentConfiguration } from '@midnight-ntwrk/testkit-js';
import type { Logger } from 'pino';
import * as Rx from 'rxjs';

const isComplete = (progress: unknown): boolean => {
  if (!progress || typeof progress !== 'object') return false;
  const candidate = progress as { isStrictlyComplete?: unknown };
  if (typeof candidate.isStrictlyComplete !== 'function') return false;
  return (candidate.isStrictlyComplete as () => boolean)();
};

const isSynced = (state: FacadeState): boolean =>
  isComplete(state.shielded.state.progress) &&
  isComplete(state.dust.state.progress) &&
  isComplete(state.unshielded.progress);

/**
 * Waits for dust to become spendable.
 *
 * Gates on the dust scan plus a positive dust balance, not on full sync: dust
 * is what actually pays the fee, and the shielded scan is irrelevant to
 * submitting a contract deployment. Reports progress, because this is the
 * longest wait in the whole flow and silence here is indistinguishable from a
 * hang.
 */
export const syncWallet = (logger: Logger, wallet: WalletFacade, throttleTime = 2_000): Promise<FacadeState> => {
  logger.info('Waiting for spendable dust...');
  let reported = 0;
  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(throttleTime),
      Rx.tap((state) => {
        reported += 1;
        if (reported % 5 === 1) {
          logger.info(
            `Waiting for dust: dust=${state.dust.balance(new Date())} ` +
              `sync{shielded=${isComplete(state.shielded.state.progress)} ` +
              `unshielded=${isComplete(state.unshielded.progress)} ` +
              `dust=${isComplete(state.dust.state.progress)}}`,
          );
        }
      }),
      Rx.filter((state) => isComplete(state.dust.state.progress) && state.dust.balance(new Date()) > 0n),
      Rx.tap((state) =>
        logger.info(
          `Dust ready: ${state.dust.balance(new Date())} (unshielded=${JSON.stringify(state.unshielded.balances)})`,
        ),
      ),
    ),
  );
};

export const unshieldedAddressOf = (state: UnshieldedWalletState): string =>
  UnshieldedAddress.codec.encode(getNetworkId(), state.address).toString();

/**
 * Waits until the unshielded address holds NIGHT, optionally asking the faucet
 * for some first. `fundFromFaucet` is off by default: it is an outbound request
 * and the caller should opt into it.
 */
export const waitForNight = async (
  logger: Logger,
  wallet: WalletFacade,
  env: EnvironmentConfiguration,
  fundFromFaucet = false,
  tokenType: UnshieldedTokenType = unshieldedToken(),
  throttleTime = 2_000,
): Promise<UnshieldedWalletState> => {
  const initial = await Rx.firstValueFrom(wallet.unshielded.state);
  logger.info(`Unshielded address: ${unshieldedAddressOf(initial)}`);

  if (fundFromFaucet) {
    if (!env.faucet) throw new Error('no faucet configured for this environment');
    logger.info('Requesting tokens from faucet...');
    await new FaucetClient(env.faucet, logger).requestTokens(unshieldedAddressOf(initial));
  }

  const balance = initial.balances[tokenType.raw];
  if (balance !== undefined && balance > 0n) {
    logger.info(`NIGHT balance: ${balance}`);
    return initial;
  }

  logger.info('No NIGHT yet -- waiting for funds to land...');

  // Report progress while waiting. Without this the process sits silent
  // indefinitely and there is no way to tell a wallet that is still scanning
  // from one that finished scanning and holds nothing -- which are completely
  // different problems: the first needs patience, the second needs funds.
  let reported = 0;
  return Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(throttleTime),
      Rx.tap((state) => {
        const balance = state.unshielded.balances[tokenType.raw] ?? 0n;
        // Report the three sub-wallets separately. "Not synced" is not one
        // condition -- shielded, unshielded and dust scan independently, and
        // knowing which is lagging is the difference between waiting and
        // debugging.
        const shielded = isComplete(state.shielded.state.progress);
        const unshielded = isComplete(state.unshielded.progress);
        const dust = isComplete(state.dust.state.progress);
        const synced = shielded && unshielded && dust;
        reported += 1;

        // Only the unshielded scan is evidence about NIGHT. Shielded and dust
        // scan from genesis and lag by minutes, but they hold no NIGHT and
        // cannot change this answer -- so waiting for them before reporting
        // just hides a conclusion that is already final.
        if (unshielded && balance === 0n) {
          // Scanning finished and there is nothing here. Left unsaid, this is
          // indistinguishable from still-scanning, and the process waits
          // forever either way. Warn on first sight, then occasionally.
          if (reported === 1 || reported % 15 === 0) {
            logger.warn(
              `The unshielded scan is COMPLETE and holds 0 NIGHT at ` +
                `${unshieldedAddressOf(state.unshielded)} on network '${getNetworkId()}'. ` +
                `This is final -- waiting longer will not change it; shielded/dust are still ` +
                `scanning but hold no NIGHT. Fund this address, or re-run with --faucet.`,
            );
          }
        } else if (reported % 5 === 1) {
          logger.info(
            `Waiting for NIGHT: balance=${balance} ` +
              `sync{shielded=${shielded} unshielded=${unshielded} dust=${dust}}`,
          );
        }
      }),
      // Gate on the unshielded scan ONLY. Requiring full sync here is wrong and
      // deadlocks: shielded and dust scan from genesis and can lag for a very
      // long time, while neither holds NIGHT and neither can change this
      // answer. Observed in practice -- balance=10000000000 with
      // sync{shielded=false unshielded=true dust=false} waited indefinitely on
      // funds that had already arrived.
      Rx.filter(
        (state) =>
          isComplete(state.unshielded.progress) &&
          (state.unshielded.balances[tokenType.raw] ?? 0n) > 0n,
      ),
      Rx.tap((state) => logger.info(`NIGHT balance: ${state.unshielded.balances[tokenType.raw]}`)),
      Rx.map((state) => state.unshielded),
    ),
  );
};

/** The HD key the unshielded keystore is built from -- role 0, account 0, index 0. */
const unshieldedSeedOf = (seed: string): Uint8Array => {
  const result = HDWallet.fromSeed(Buffer.from(seed, 'hex'));
  if (result.type !== 'seedOk') throw new Error('seed rejected by HDWallet');
  const derived = result.hdWallet.selectAccount(0).selectRole(Roles.NightExternal).deriveKeyAt(0);
  if (derived.type !== 'keyDerived') throw new Error('key derivation out of bounds');
  return derived.key;
};

/**
 * Registers unregistered NIGHT UTXOs for dust generation, so the wallet can pay
 * fees. Returns the tx id, or undefined when there was nothing to register.
 */
export const registerForDust = async (
  logger: Logger,
  seed: string,
  unshielded: UnshieldedWalletState,
  wallet: WalletFacade,
): Promise<string | undefined> => {
  const utxos = unshielded.availableCoins.filter((coin) => !coin.meta.registeredForDustGeneration);
  if (utxos.length === 0) {
    logger.info('All NIGHT UTXOs are already registered for dust generation.');
    return undefined;
  }

  const dustState = await wallet.dust.waitForSyncedState();
  const keystore = createKeystore(unshieldedSeedOf(seed), getNetworkId());

  logger.info(`Registering ${utxos.length} UTXO(s) for dust generation...`);
  const recipe = await wallet.registerNightUtxosForDustGeneration(
    utxos,
    keystore.getPublicKey(),
    (payload) => keystore.signData(payload),
    dustState.address,
  );
  const txId = await wallet.submitTransaction(await wallet.finalizeRecipe(recipe));
  logger.info(`Dust registration submitted: ${txId}`);

  const dustBalance = await Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.filter((s) => s.dust.balance(new Date()) > 0n),
      Rx.map((s) => s.dust.balance(new Date())),
    ),
  );
  logger.info(`Dust balance: ${dustBalance}`);
  return txId;
};
